version: 2
jobs:
  test:
    working_directory: ~/bespoke-highlightjs
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - persist_to_workspace:
          root: ~/bespoke-highlightjs
          paths: .
  deploy:
    working_directory: ~/bespoke-highlightjs
    docker:
      - image: circleci/node:10.5.0
    steps:
      - attach_workspace:
          at: ~/bespoke-highlightjs
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/bespoke-highlightjs/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
